### PR TITLE
Fix The implementation of Api

### LINKED ISSUE #7: Fix The implementation of Api

### PR DESCRIPTION
**Pull request by AhmedShaabanElhdad**

### CODE REVIEW

File: api.go [hunk 1]
```diff
@@ -35,9 +35,13 @@ func NewApiServer(listentAddr string, store Storage) *APIServer {
 func (s *APIServer) Run() {
 	router := mux.NewRouter()
 
-	router.HandleFunc("/account", makeHttpHandlerFunc(s.handleAccount))
+	router.HandleFunc("/login", makeHttpHandlerFunc(s.handleLogin))
```
Comment (AhmedShaabanElhdad) [inline api.go:38]: nice 👌

File: api.go [hunk 2]
```diff
@@ -35,9 +35,13 @@ func NewApiServer(listentAddr string, store Storage) *APIServer {
...
 
-	router.HandleFunc("/account/{id}", makeHttpHandlerFunc(s.handleSpecificAccount))
+	router.HandleFunc("/account", withJwtAuth(makeHttpHandlerFunc(s.handleAccount)))
+
+	router.HandleFunc("/createAccount", makeHttpHandlerFunc(s.handleCreateAccount))
```
Comment (AhmedShaabanElhdad) [inline api.go:42]: nice 👌

File: api.go [hunk 3]
```diff
@@ -52,19 +56,47 @@ func (s *APIServer) Run() {
 func (s *APIServer) handleAccount(w http.ResponseWriter, r *http.Request) error {
 	if r.Method == "PUT" {
 		return s.handleUpdateccount(w, r)
+	} else if r.Method == "DELETE" {
```
Comment (AhmedShaabanElhdad) [inline api.go:59]: nice 👌

File: api.go [hunk 4]
```diff
@@ -52,19 +56,47 @@ func (s *APIServer) Run() {
...
-		return s.handleCreateAccount(w, r)
-	}
-	if r.Method == "DELETE" {
-		return s.handleDeleteAccount(w, r)
+		var request LoginRequest
+		if err := json.NewDecoder(r.Body).Decode(&request); err != nil {
+			return err
+		}
+
+		account, err := s.store.GetAccountByNumber(request.Number)
```
Comment (AhmedShaabanElhdad) [inline api.go:73]: nice 👌

File: api.go [hunk 5]
```diff
@@ -52,19 +56,47 @@ func (s *APIServer) Run() {
...
+		if err != nil {
+			return fmt.Errorf("number or password doesn't exist")
+		}
+
+		if !account.validatePassword(request.Password) {
```
Comment (AhmedShaabanElhdad) [inline api.go:78]: nice 👌

File: api.go [hunk 6]
```diff
@@ -52,19 +56,47 @@ func (s *APIServer) Run() {
...
+			// return err
+			return fmt.Errorf("number or password doesn't exist")
+		}
+
+		token, err := createJwtAuth(account)
+		if err != nil {
```
Comment (AhmedShaabanElhdad) [inline api.go:84]: nice 👌

File: api.go [hunk 7]
```diff
@@ -89,29 +121,36 @@ func (s *APIServer) handleGetAccounts(w http.ResponseWriter, r *http.Request) er
...
-	if err := s.store.CreateAccount(account); err != nil {
-		return err
+	if r.Method == "POST" {
+		createAccountRequest := new(CreateAccountRequest) // -->  return pointer and will use it in json and other stuff so better to use pointer
+		// createAccountRequest := CreateAccountRequest{}    --> return instance not pointer so will need to use &createAccountRequest
+		if err := json.NewDecoder(r.Body).Decode(createAccountRequest); err != nil {
+			return err
+		}
+		defer r.Body.Close()
+		account, err := NewAccount(
```
Comment (AhmedShaabanElhdad) [inline api.go:131]: nice 👌

File: api.go [hunk 8]
```diff
@@ -89,29 +121,36 @@ func (s *APIServer) handleGetAccounts(w http.ResponseWriter, r *http.Request) er
...
+			createAccountRequest.FirstName,
+			createAccountRequest.LastName,
+			createAccountRequest.Password,
+		)
+		if err != nil {
+			return err
+		}
+		if err := s.store.CreateAccount(account); err != nil {
```
Comment (AhmedShaabanElhdad) [inline api.go:139]: nice 👌

File: api.go [hunk 9]
```diff
@@ -135,21 +174,22 @@ func (s *APIServer) handleTransfer(w http.ResponseWriter, r *http.Request) error
 
 }
 
-func getID(r *http.Request) (int, error) {
-	idStr := mux.Vars(r)["id"]
+func getNumber(r *http.Request) (int, error) {
```
Comment (AhmedShaabanElhdad) [inline api.go:177]: nice 👌

File: api.go [hunk 10]
```diff
@@ -190,8 +236,9 @@ func createJwtAuth(account *Account) (string, error) {
 	// Create the Claims
 	//  use &jwt.RegisteredClaims is create Claim with Standard value
 	claims := &jwt.MapClaims{
-		"ExpiresAt": jwt.NewNumericDate(time.Unix(1516239022, 0)),
-		"AccountId": account.ID,
+		"ExpiresAt":     jwt.NewNumericDate(time.Unix(1516239022, 0)),
```
Comment (AhmedShaabanElhdad) [inline api.go:239]: nice 👌

File: go.mod [hunk 11]
```diff
@@ -4,6 +4,18 @@ go 1.22.4
...
 require github.com/gorilla/mux v1.8.1
 
-require github.com/lib/pq v1.10.9
+require (
+	github.com/lib/pq v1.10.9
+	golang.org/x/crypto v0.25.0
+)
 
-require github.com/golang-jwt/jwt/v5 v5.2.1 // indirect
+require (
```
Comment (AhmedShaabanElhdad) [inline go.mod:12]: nice 👌

File: types.go [hunk 12]
```diff
@@ -17,20 +30,30 @@ type TransferRequest struct {
...
+func (a *Account) validatePassword(password string) bool {
+	return bcrypt.CompareHashAndPassword([]byte(a.EncryptedPassword), []byte(password)) == nil
+}
+
+func NewAccount(firstName string, lastName string, password string) (*Account, error) {
+	encryptedPass, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
+	if err != nil {
+		return nil, err
 	}
+	return &Account{
```
Comment (AhmedShaabanElhdad) [inline types.go:51]: nice 👌

File: types.go [hunk 13]
```diff
@@ -17,20 +30,30 @@ type TransferRequest struct {
...
 }
 
-func NewAccount(firstName string, lastName string) *Account {
-	return &Account{
-		ID:        rand.Intn(10000),
-		FirstName: firstName,
-		LastName:  lastName,
-		Number:    int64(rand.Intn(10000000)),
-		CreatedAt: time.Now().UTC(),
+func (a *Account) validatePassword(password string) bool {
```
Comment (AhmedShaabanElhdad) [inline types.go:42]: nice 👌

File: types.go [hunk 14]
```diff
@@ -17,20 +30,30 @@ type TransferRequest struct {
...
+	return bcrypt.CompareHashAndPassword([]byte(a.EncryptedPassword), []byte(password)) == nil
+}
+
+func NewAccount(firstName string, lastName string, password string) (*Account, error) {
```
Comment (AhmedShaabanElhdad) [inline types.go:46]: nice 👌

File: types.go [hunk 15]
```diff
@@ -17,20 +30,30 @@ type TransferRequest struct {
 }
 
 type Account struct {
-	ID        int       `json:"id"`
-	Number    int64     `json:"number"`
-	FirstName string    `json:"firstName"`
-	LastName  string    `json:"lastName"`
-	Balance   int64     `json:"balance"`
-	CreatedAt time.Time `json:"createdAt"`
+	ID                int       `json:"id"`
```
Comment (AhmedShaabanElhdad) [inline types.go:33]: nice 👌

File: types.go [hunk 16]
```diff
@@ -3,11 +3,24 @@ package main
...
 	"math/rand"
 	"time"
+
+	"golang.org/x/crypto/bcrypt"
 )
 
 type CreateAccountRequest struct {
 	FirstName string `json:"firstName"`
 	LastName  string `json:"lastName"`
+	Password  string `json:"password"`
```
Comment (AhmedShaabanElhdad) [inline types.go:13]: nice 👌

File: storage.go [hunk 17]
```diff
@@ -7,11 +7,13 @@ import (
 	_ "github.com/lib/pq"
 )
 
+// need to think of way to better solution as interface increase in size
 type Storage interface {
 	CreateAccount(*Account) error
 	DeleteAccount(int) error
 	UpdateAccount(*Account) error
 	GetAccountByID(int) (*Account, error)
+	GetAccountByNumber(int64) (*Account, error)
```
Comment (AhmedShaabanElhdad) [inline storage.go:16]: nice 👌

File: script/seeds/main.go [hunk 18]
```diff
@@ -0,0 +1,21 @@
+package main
```
Comment (AhmedShaabanElhdad) [inline script/seeds/main.go:1]: nice 👌

File: main.go [hunk 19]
```diff
@@ -16,6 +21,28 @@ func main() {
...
+		fmt.Println("seeding account to DB")
+		seedAccounts(store)
+	}
+
+	server := NewApiServer(":3001", store)
+	fmt.Printf("connect to the server : localhost:30001/")
 	server.Run()
 }
+
+func seedAccount(store Storage, fname string, lname string, password string) *Account {
```
Comment (AhmedShaabanElhdad) [inline main.go:34]: nice 👌

File: main.go [hunk 20]
```diff
@@ -16,6 +21,28 @@ func main() {
 		log.Fatal(err)
 	}
 
-	server := NewApiServer(":3000", store)
+	if *seed {
```
Comment (AhmedShaabanElhdad) [inline main.go:24]: nice 👌

File: go.mod [hunk 21]
```diff
@@ -4,6 +4,18 @@ go 1.22.4
...
+	github.com/golang-jwt/jwt/v5 v5.2.1
+	github.com/stretchr/testify v1.9.0
+)
+
+require (
```
Comment (AhmedShaabanElhdad) [inline go.mod:17]: nice 👌
